apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - git::https://github.com/kubernetes/ingress-nginx//deploy/static/provider/baremetal?ref=controller-v1.2.0

patchesJson6902:
  - target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
      version: v1
    path: hardcode_nodeport.patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: IngressClass
      name: nginx
    path: set_default_ingress_class.patch.yml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ingress-nginx-controller
    namespace: ingress-nginx
    behavior: merge
    envs:
      - config.env
  - name: custom-headers
    namespace: ingress-nginx
    envs:
      - headers.env
